title: Revista Tempovani
tagline: Dono do próprio nariz
description: Revista Tempovani — artigos, ensaios e reportagens
url: ""
baseurl: ""
permalink: /artigos/:title/
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Revista Tempovani"
